# Generated by Django 4.1.1 on 2023-05-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='image',
            field=models.ImageField(upload_to='upload/images'),
        ),
    ]
