# Generated by Django 4.1.1 on 2023-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_add_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
