# Generated by Django 4.1.1 on 2023-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_delete_add_nft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='add',
            name='nft_name',
            field=models.CharField(max_length=50),
        ),
    ]
