# Generated by Django 4.1.1 on 2023-05-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_add_name_alter_add_nft_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
    ]
